# Generated by Django 4.2 on 2024-01-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'permissions': [('can_borrow', 'Can borrow books'), ('can_return', 'Can return books')]},
        ),
    ]
