# Generated by Django 4.2 on 2024-01-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_alter_borrowing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='email',
        ),
    ]
