name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGREDB_HOST: localhost
          POSTGREDB_PORT: 5432
          POSTGREDB_NAME: mydatabase
          POSTGREDB_USER: myuser
          POSTGREDB_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydatabase
        POSTGREDB_HOST: localhost
        POSTGREDB_PORT: 5432
        POSTGREDB_NAME: mydatabase
        POSTGREDB_USER: myuser
        POSTGREDB_PASSWORD: mypassword
      run: |
        python manage.py test
